// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1HKOs9q3a5pdODM-bdMdYbOaF1Ou7UK8',
    appId: '1:839530592593:web:e157677bfee795f78d3b70',
    messagingSenderId: '839530592593',
    projectId: 'mmlaka-6ea7c',
    authDomain: 'mmlaka-6ea7c.firebaseapp.com',
    storageBucket: 'mmlaka-6ea7c.firebasestorage.app',
    measurementId: 'G-WE16D152ZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXJGF26dBxDkPUu8adUUv69fAGx73Rbp0',
    appId: '1:839530592593:android:f29c6f1a08489bfc8d3b70',
    messagingSenderId: '839530592593',
    projectId: 'mmlaka-6ea7c',
    storageBucket: 'mmlaka-6ea7c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxVDcXJupRxOtoB1Hn60lyI_cf90rkQYM',
    appId: '1:839530592593:ios:21587ca040bb305f8d3b70',
    messagingSenderId: '839530592593',
    projectId: 'mmlaka-6ea7c',
    storageBucket: 'mmlaka-6ea7c.firebasestorage.app',
    iosBundleId: 'com.example.appm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxVDcXJupRxOtoB1Hn60lyI_cf90rkQYM',
    appId: '1:839530592593:ios:21587ca040bb305f8d3b70',
    messagingSenderId: '839530592593',
    projectId: 'mmlaka-6ea7c',
    storageBucket: 'mmlaka-6ea7c.firebasestorage.app',
    iosBundleId: 'com.example.appm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1HKOs9q3a5pdODM-bdMdYbOaF1Ou7UK8',
    appId: '1:839530592593:web:7d9de565ad6301228d3b70',
    messagingSenderId: '839530592593',
    projectId: 'mmlaka-6ea7c',
    authDomain: 'mmlaka-6ea7c.firebaseapp.com',
    storageBucket: 'mmlaka-6ea7c.firebasestorage.app',
    measurementId: 'G-5VZT7KG0YL',
  );
}
